### ISSUE TITLE
update from es5 to es6

### ISSUE THREAD

**Issue by johnengleman** [aicccia/todo-app-with-filtering#1]
- [x] copy es5 code
- [x] review es6 features
- [x] scan through copied es5 code for parts that can be upgrades

**Comment by nicholasengleman** [comment]
- [ ] copy es5 code
- [ ] review es6 features
- [ ] scan through copied es5 code for parts that can be upgrades

**Comment by johnengleman** [comment]
completed: 88392eb25486af3b1497472e0ccb770d2452322e
